export const signUpCountries = [
  { "countryCode": "AF", "countryName": "Afghanistan" },
  { "countryCode": "AL", "countryName": "Albania" },
  { "countryCode": "DZ", "countryName": "Algeria" },
  { "countryCode": "AD", "countryName": "Andorra" },
  { "countryCode": "AO", "countryName": "Angola" },
  { "countryCode": "AG", "countryName": "Antigua and Barbuda" },
  { "countryCode": "AR", "countryName": "Argentina" },
  { "countryCode": "AM", "countryName": "Armenia" },
  { "countryCode": "AU", "countryName": "Australia" },
  { "countryCode": "AT", "countryName": "Austria" },
  { "countryCode": "AZ", "countryName": "Azerbaijan" },
  { "countryCode": "BS", "countryName": "Bahamas" },
  { "countryCode": "BH", "countryName": "Bahrain" },
  { "countryCode": "BD", "countryName": "Bangladesh" },
  { "countryCode": "BB", "countryName": "Barbados" },
  { "countryCode": "BY", "countryName": "Belarus" },
  { "countryCode": "BE", "countryName": "Belgium" },
  { "countryCode": "BZ", "countryName": "Belize" },
  { "countryCode": "BJ", "countryName": "Benin" },
  { "countryCode": "BT", "countryName": "Bhutan" },
  { "countryCode": "BO", "countryName": "Bolivia" },
  { "countryCode": "BA", "countryName": "Bosnia and Herzegovina" },
  { "countryCode": "BW", "countryName": "Botswana" },
  { "countryCode": "BR", "countryName": "Brazil" },
  { "countryCode": "BN", "countryName": "Brunei" },
  { "countryCode": "BG", "countryName": "Bulgaria" },
  { "countryCode": "BF", "countryName": "Burkina Faso" },
  { "countryCode": "BI", "countryName": "Burundi" },
  { "countryCode": "KH", "countryName": "Cambodia" },
  { "countryCode": "CM", "countryName": "Cameroon" },
  { "countryCode": "CA", "countryName": "Canada" },
  { "countryCode": "CV", "countryName": "Cape Verde" },
  { "countryCode": "CF", "countryName": "Central African Republic" },
  { "countryCode": "TD", "countryName": "Chad" },
  { "countryCode": "CL", "countryName": "Chile" },
  { "countryCode": "CN", "countryName": "China" },
  { "countryCode": "CO", "countryName": "Colombia" },
  { "countryCode": "KM", "countryName": "Comoros" },
  { "countryCode": "CG", "countryName": "Congo (Brazzaville)" },
  { "countryCode": "CD", "countryName": "Congo (Kinshasa)" },
  { "countryCode": "CR", "countryName": "Costa Rica" },
  { "countryCode": "HR", "countryName": "Croatia" },
  { "countryCode": "CU", "countryName": "Cuba" },
  { "countryCode": "CY", "countryName": "Cyprus" },
  { "countryCode": "CZ", "countryName": "Czechia" },
  { "countryCode": "DK", "countryName": "Denmark" },
  { "countryCode": "DJ", "countryName": "Djibouti" },
  { "countryCode": "DM", "countryName": "Dominica" },
  { "countryCode": "DO", "countryName": "Dominican Republic" },
  { "countryCode": "EC", "countryName": "Ecuador" },
  { "countryCode": "EG", "countryName": "Egypt" },
  { "countryCode": "SV", "countryName": "El Salvador" },
  { "countryCode": "GQ", "countryName": "Equatorial Guinea" },
  { "countryCode": "ER", "countryName": "Eritrea" },
  { "countryCode": "EE", "countryName": "Estonia" },
  { "countryCode": "ET", "countryName": "Ethiopia" },
  { "countryCode": "FJ", "countryName": "Fiji" },
  { "countryCode": "FI", "countryName": "Finland" },
  { "countryCode": "FR", "countryName": "France" },
  { "countryCode": "GA", "countryName": "Gabon" },
  { "countryCode": "GM", "countryName": "Gambia" },
  { "countryCode": "GE", "countryName": "Georgia" },
  { "countryCode": "DE", "countryName": "Germany" },
  { "countryCode": "GH", "countryName": "Ghana" },
  { "countryCode": "GR", "countryName": "Greece" },
  { "countryCode": "GD", "countryName": "Grenada" },
  { "countryCode": "GT", "countryName": "Guatemala" },
  { "countryCode": "GN", "countryName": "Guinea" },
  { "countryCode": "GW", "countryName": "Guinea-Bissau" },
  { "countryCode": "GY", "countryName": "Guyana" },
  { "countryCode": "HT", "countryName": "Haiti" },
  { "countryCode": "HN", "countryName": "Honduras" },
  { "countryCode": "HU", "countryName": "Hungary" },
  { "countryCode": "IS", "countryName": "Iceland" },
  { "countryCode": "IN", "countryName": "India" },
  { "countryCode": "ID", "countryName": "Indonesia" },
  { "countryCode": "IR", "countryName": "Iran" },
  { "countryCode": "IQ", "countryName": "Iraq" },
  { "countryCode": "IE", "countryName": "Ireland" },
  { "countryCode": "IT", "countryName": "Italy" },
  { "countryCode": "JM", "countryName": "Jamaica" },
  { "countryCode": "JP", "countryName": "Japan" },
  { "countryCode": "JO", "countryName": "Jordan" },
  { "countryCode": "KZ", "countryName": "Kazakhstan" },
  { "countryCode": "KE", "countryName": "Kenya" },
  { "countryCode": "KI", "countryName": "Kiribati" },
  { "countryCode": "KW", "countryName": "Kuwait" },
  { "countryCode": "KG", "countryName": "Kyrgyzstan" },
  { "countryCode": "LA", "countryName": "Laos" },
  { "countryCode": "LV", "countryName": "Latvia" },
  { "countryCode": "LB", "countryName": "Lebanon" },
  { "countryCode": "LS", "countryName": "Lesotho" },
  { "countryCode": "LR", "countryName": "Liberia" },
  { "countryCode": "LY", "countryName": "Libya" },
  { "countryCode": "LI", "countryName": "Liechtenstein" },
  { "countryCode": "LT", "countryName": "Lithuania" },
  { "countryCode": "LU", "countryName": "Luxembourg" }
];
